apiVersion: v1
metadata:
  name: {{ include "metabase.fullname" . }}-secrets
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
type: Opaque
stringData:
  MB_DB_HOST: {{ .Values.secrets.database.host | quote }}
  MB_DB_PASS: {{ .Values.secrets.database.password | quote }}
  MB_DB_USER: {{ .Values.secrets.database.username | quote }}
  MB_DB_DBNAME: {{ .Values.secrets.database.dbName | quote }}
  MB_DB_PORT: {{ .Values.secrets.database.port | quote }}
  MB_ENCRYPTION_SECRET_KEY: {{ .Values.secrets.config.encryptionKey | quote }}
  MB_DB_CONNECTION_URI: {{ .Values.secrets.database.connString | quote }}
  MB_EMAIL_SMTP_HOST: {{ .Values.secrets.email.host | quote }}
  MB_EMAIL_SMTP_USERNAME: {{ .Values.secrets.email.username | quote }}
  MB_EMAIL_SMTP_PASSWORD: {{ .Values.secrets.email.password | quote }}
  MB_EMAIL_SMTP_PORT: {{ .Values.secrets.email.port | quote }}
  MB_EMAIL_SMTP_SECURITY: {{ .Values.secrets.email.security | quote }}
  MB_JWT_SHARED_SECRET
  MB_LDAP_HOST
  MB_LDAP_PASSWORD
  MB_LDAP_PORT
  MB_LDAP_SECURITY
  MB_PREMIUM_EMBEDDING_TOKEN
  MB_QP_CACHE_BACKEND
  MB_SAML_IDENTITY_PROVIDER_CERTIFICATE
  MB_SETUP_TOKEN
  MB_SLACK_TOKEN
kind: Secret